# f1 = Player.new({'first_name' => 'Fabien', 'last_name' => 'Barthez', 'country_id' => team1.id, 'position' => 'Goalkeeper', 'goals' => 0})
# f2 = Player.new({'first_name' => 'Lilian', 'last_name' => 'Thuram', 'country_id' => team1.id, 'position' => 'Defender', 'goals' => 0})
# f3 = Player.new({'first_name' => 'Marcel', 'last_name' => 'Desailly', 'country_id' => team1.id, 'position' => 'Defender', 'goals' => 0})
# f4 = Player.new({'first_name' => 'Frank', 'last_name' => 'Leboeuf', 'country_id' => team1.id, 'position' => 'Defender', 'goals' => 0})
# f5 = Player.new({'first_name' => 'Bixente', 'last_name' => 'Lizarazu', 'country_id' => team1.id, 'position' => 'Defender', 'goals' => 0})
# f6 = Player.new({'first_name' => 'Christian', 'last_name' => 'Karembeu', 'country_id' => team1.id, 'position' => 'Midfielder', 'goals' => 0})
# f7 = Player.new({'first_name' => 'Didier', 'last_name' => 'Deschamps', 'country_id' => team1.id, 'position' => 'Midfielder', 'goals' => 0})
# f8 = Player.new({'first_name' => 'Youri', 'last_name' => 'Djorkaeff', 'country_id' => team1.id, 'position' => 'Midfielder', 'goals' => 0})
# f9 = Player.new({'first_name' => 'Emmanuel', 'last_name' => 'Petit', 'country_id' => team1.id, 'position' => 'Midfielder', 'goals' => 0})
# f10 = Player.new({'first_name' => 'Zinedine','last_name' => 'Zidane', 'country_id' => team1.id, 'position' => 'Midfielder', 'goals' => 0})
# f11 = Player.new({'first_name' => 'Stephane','last_name' => 'Guivarch', 'country_id' => team1.id, 'position' => 'Striker', 'goals' => 0})

# b1 = Player.new({'first_name' => 'Claudio', 'last_name' => 'Taffarel', 'country_id' => team2.id, 'position' => 'Goalkeeper', 'goals' => 0})
# b2 = Player.new({'first_name' => nil, 'last_name' => 'Cafu', 'country_id' => team2.id, 'position' => 'Defender', 'goals' => 0})
# b3 = Player.new({'first_name' => nil, 'last_name' => 'Aldair', 'country_id' => team2.id, 'position' => 'Defender', 'goals' => 0})
# b4 = Player.new({'first_name' => 'Junior', 'last_name' => 'Baiano', 'country_id' => team2.id, 'position' => 'Defender', 'goals' => 0})
# b5 = Player.new({'first_name' => 'Roberto', 'last_name' => 'Carlos', 'country_id' => team2.id, 'position' => 'Defender', 'goals' => 0})
# b6 = Player.new({'first_name' => 'Cesar', 'last_name' => 'Sampaio', 'country_id' => team2.id, 'position' => 'Midfielder', 'goals' => 0})
# b7 = Player.new({'first_name' => nil, 'last_name' => 'Dunga', 'country_id' => team2.id, 'position' => 'Midfielder', 'goals' => 0})
# b8 = Player.new({'first_name' => nil, 'last_name' => 'Rivaldo', 'country_id' => team2.id, 'position' => 'Midfielder', 'goals' => 0})
# b9 = Player.new({'first_name' => nil, 'last_name' => 'Leonardo', 'country_id' => team2.id, 'position' => 'Midfielder', 'goals' => 0})
# b10 = Player.new({'first_name' => nil, 'last_name' => 'Bebeto', 'country_id' => team2.id, 'position' => 'Striker', 'goals' => 0})
# b11 = Player.new({'first_name' => nil, 'last_name' => 'Ronaldo', 'country_id' => team2.id, 'position' => 'Striker', 'goals' => 0})

# c1 = Player.new({'first_name' => 'Drazen', 'last_name' => 'Ladic', 'country_id' => team3.id, 'position' => 'Goalkeeper', 'goals' => 0})
# c2 = Player.new({'first_name' => 'Igor', 'last_name' => 'Stimac', 'country_id' => team3.id, 'position' => 'Defender', 'goals' => 0})
# c3 = Player.new({'first_name' => 'Dario', 'last_name' => 'Simic', 'country_id' => team3.id, 'position' => 'Defender', 'goals' => 0})
# c4 = Player.new({'first_name' => 'Slaven', 'last_name' => 'Bilic', 'country_id' => team3.id, 'position' => 'Defender', 'goals' => 0})
# c5 = Player.new({'first_name' => 'Mario', 'last_name' => 'Stanic', 'country_id' => team3.id, 'position' => 'Defender', 'goals' => 0})
# c6 = Player.new({'first_name' => 'Robert', 'last_name' => 'Jarni', 'country_id' => team3.id, 'position' => 'Defender', 'goals' => 0})
# c7 = Player.new({'first_name' => 'Zvonimir', 'last_name' => 'Soldo', 'country_id' => team3.id, 'position' => 'Midfielder', 'goals' => 0})
# c8 = Player.new({'first_name' => 'Aljosa', 'last_name' => 'Asanovic', 'country_id' => team3.id, 'position' => 'Midfielder', 'goals' => 0})
# c9 = Player.new({'first_name' => 'Zvonimir', 'last_name' => 'Boban', 'country_id' => team3.id, 'position' => 'Midfielder', 'goals' => 0})
# c10 = Player.new({'first_name' => 'Robert','last_name' => 'Prosinecki', 'country_id' => team3.id, 'position' => 'Striker', 'goals' => 0})
# c11 = Player.new({'first_name' => 'Davor','last_name' => 'Suker', 'country_id' => team3.id, 'position' => 'Striker', 'goals' => 0})

# n1 = Player.new({'first_name' => 'Edwin', 'last_name' => 'van der Sar', 'country_id' => team4.id, 'position' => 'Goalkeeper', 'goals' => 0})
# n2 = Player.new({'first_name' => 'Michael', 'last_name' => 'Reiziger', 'country_id' => team4.id, 'position' => 'Defender', 'goals' => 0})
# n3 = Player.new({'first_name' => 'Jaap', 'last_name' => 'Stam', 'country_id' => team4.id, 'position' => 'Defender', 'goals' => 0})
# n4 = Player.new({'first_name' => 'Frank', 'last_name' => 'de Boer', 'country_id' => team4.id, 'position' => 'Defender', 'goals' => 0})
# n5 = Player.new({'first_name' => 'Artur', 'last_name' => 'Numan', 'country_id' => team4.id, 'position' => 'Defender', 'goals' => 0})
# n6 = Player.new({'first_name' => 'Wim', 'last_name' => 'Jonk', 'country_id' => team4.id, 'position' => 'Midfielder', 'goals' => 0})
# n7 = Player.new({'first_name' => 'Edgar', 'last_name' => 'Davids', 'country_id' => team4.id, 'position' => 'Midfielder', 'goals' => 0})
# n8 = Player.new({'first_name' => 'Ronald', 'last_name' => 'de Boer', 'country_id' => team4.id, 'position' => 'Midfielder', 'goals' => 0})
# n9 = Player.new({'first_name' => 'Philip', 'last_name' => 'Cocu', 'country_id' => team4.id, 'position' => 'Midfielder', 'goals' => 0})
# n10 = Player.new({'first_name' => 'Dennis', 'last_name' => 'Bergkamp', 'country_id' => team4.id, 'position' => 'Striker', 'goals' => 0})
# n11 = Player.new({'first_name' => 'Patrick', 'last_name' => 'Kluivert', 'country_id' => team4.id, 'position' => 'Striker', 'goals' => 0})

# s1 = Player.new({'first_name' => 'Jim', 'last_name' => 'Leighton', 'country_id' => team5.id, 'position' => 'Goalkeeper', 'goals' => 0})
# s2 = Player.new({'first_name' => 'Tom', 'last_name' => 'Boyd', 'country_id' => team5.id, 'position' => 'Defender', 'goals' => 0})
# s3 = Player.new({'first_name' => 'Colin', 'last_name' => 'Calderwood', 'country_id' => team5.id, 'position' => 'Defender', 'goals' => 0})
# s4 = Player.new({'first_name' => 'Colin', 'last_name' => 'Hendry', 'country_id' => team5.id, 'position' => 'Defender', 'goals' => 0})
# s5 = Player.new({'first_name' => 'Christian', 'last_name' => 'Dailly', 'country_id' => team5.id, 'position' => 'Defender', 'goals' => 0})
# s6 = Player.new({'first_name' => 'Paul', 'last_name' => 'Lambert', 'country_id' => team5.id, 'position' => 'Midfielder', 'goals' => 0})
# s7 = Player.new({'first_name' => 'Craig', 'last_name' => 'Burley', 'country_id' => team5.id, 'position' => 'Midfielder', 'goals' => 0})
# s8 = Player.new({'first_name' => 'John', 'last_name' => 'Collins', 'country_id' => team5.id, 'position' => 'Midfielder', 'goals' => 0})
# s9 = Player.new({'first_name' => 'Kevin', 'last_name' => 'Gallacher', 'country_id' => team5.id, 'position' => 'Striker', 'goals' => 0})
# s10 = Player.new({'first_name' => 'Gordon', 'last_name' => 'Durie', 'country_id' => team5.id, 'position' => 'Striker', 'goals' => 0})
# s11 = Player.new({'first_name' => 'Darren', 'last_name' => 'Jackson', 'country_id' => team5.id, 'position' => 'Striker', 'goals' => 0})

# ni1 = Player.new({'first_name' => 'Peter', 'last_name' => 'Rufai', 'country_id' => team6.id, 'position' => 'Goalkeeper', 'goals' => 0})
# ni2 = Player.new({'first_name' => 'Mutiu', 'last_name' => 'Adepoju', 'country_id' => team6.id, 'position' => 'Defender', 'goals' => 0})
# ni3 = Player.new({'first_name' => 'Taribo', 'last_name' => 'West', 'country_id' => team6.id, 'position' => 'Defender', 'goals' => 0})
# ni4 = Player.new({'first_name' => 'Uche', 'last_name' => 'Okechukwu', 'country_id' => team6.id, 'position' => 'Defender', 'goals' => 0})
# ni5 = Player.new({'first_name' => 'Celestine', 'last_name' => 'Babayaro', 'country_id' => team6.id, 'position' => 'Defender', 'goals' => 0})
# ni6 = Player.new({'first_name' => 'Sunday', 'last_name' => 'Oliseh', 'country_id' => team6.id, 'position' => 'Midfielder', 'goals' => 0})
# ni7 = Player.new({'first_name' => 'Finidi', 'last_name' => 'George', 'country_id' => team6.id, 'position' => 'Midfielder', 'goals' => 0})
# ni8 = Player.new({'first_name' => 'Garba', 'last_name' => 'Lawal', 'country_id' => team6.id, 'position' => 'Midfielder', 'goals' => 0})
# ni9 = Player.new({'first_name' => 'Jay Jay', 'last_name' => 'Okocha', 'country_id' => team6.id, 'position' => 'Midfielder', 'goals' => 0})
# ni10 = Player.new({'first_name' => 'Nwankwo', 'last_name' => 'Kanu', 'country_id' => team6.id, 'position' => 'Striker', 'goals' => 0})
# ni11 = Player.new({'first_name' => 'Victor', 'last_name' => 'Ikpeba', 'country_id' => team6.id, 'position' => 'Striker', 'goals' => 0})

# i1 = Player.new({'first_name' => 'Gianluca', 'last_name' => 'Pagliuca', 'country_id' => team7.id, 'position' => 'Goalkeeper', 'goals' => 0})
# i2 = Player.new({'first_name' => 'Alessandro', 'last_name' => 'Costacurta', 'country_id' => team7.id, 'position' => 'Defender', 'goals' => 0})
# i3 = Player.new({'first_name' => 'Fabio', 'last_name' => 'Cannavaro', 'country_id' => team7.id, 'position' => 'Defender', 'goals' => 0})
# i4 = Player.new({'first_name' => 'Alessandro', 'last_name' => 'Nesta', 'country_id' => team7.id, 'position' => 'Defender', 'goals' => 0})
# i5 = Player.new({'first_name' => 'Paolo', 'last_name' => 'Maldini', 'country_id' => team7.id, 'position' => 'Defender', 'goals' => 0})
# i6 = Player.new({'first_name' => 'Dino', 'last_name' => 'Baggio', 'country_id' => team7.id, 'position' => 'Midfielder', 'goals' => 0})
# i7 = Player.new({'first_name' => 'Demetrio', 'last_name' => 'Albertini', 'country_id' => team7.id, 'position' => 'Midfielder', 'goals' => 0})
# i8 = Player.new({'first_name' => 'Luigi', 'last_name' => 'Di Biagio', 'country_id' => team7.id, 'position' => 'Midfielder', 'goals' => 0})
# i9 = Player.new({'first_name' => 'Francesco', 'last_name' => 'Moriero', 'country_id' => team7.id, 'position' => 'Midfielder', 'goals' => 0})
# i10 = Player.new({'first_name' => 'Roberto', 'last_name' => 'Baggio', 'country_id' => team7.id, 'position' => 'Striker', 'goals' => 0})
# i11 = Player.new({'first_name' => 'Christian', 'last_name' => 'Vieri', 'country_id' => team7.id, 'position' => 'Striker', 'goals' => 0})

# a1 = Player.new({'first_name' => 'Carlos', 'last_name' => 'Roa', 'country_id' => team8.id, 'position' => 'Goalkeeper', 'goals' => 0})
# a2 = Player.new({'first_name' => 'Javier', 'last_name' => 'Zanetti', 'country_id' => team8.id, 'position' => 'Defender', 'goals' => 0})
# a3 = Player.new({'first_name' => 'Roberto', 'last_name' => 'Ayala', 'country_id' => team8.id, 'position' => 'Defender', 'goals' => 0})
# a4 = Player.new({'first_name' => 'Jose', 'last_name' => 'Chamot', 'country_id' => team8.id, 'position' => 'Defender', 'goals' => 0})
# a5 = Player.new({'first_name' => 'Roberto', 'last_name' => 'Sensini', 'country_id' => team8.id, 'position' => 'Defender', 'goals' => 0})
# a6 = Player.new({'first_name' => 'Matias', 'last_name' => 'Almeyda', 'country_id' => team8.id, 'position' => 'Midfielder', 'goals' => 0})
# a7 = Player.new({'first_name' => 'Diego', 'last_name' => 'Simeone', 'country_id' => team8.id, 'position' => 'Midfielder', 'goals' => 0})
# a8 = Player.new({'first_name' => 'Juan Sebastian', 'last_name' => 'Veron', 'country_id' => team8.id, 'position' => 'Midfielder', 'goals' => 0})
# a9 = Player.new({'first_name' => 'Ariel', 'last_name' => 'Ortega', 'country_id' => team8.id, 'position' => 'Midfielder', 'goals' => 0})
# a10 = Player.new({'first_name' => 'Claudio', 'last_name' => 'Lopez', 'country_id' => team8.id, 'position' => 'Striker', 'goals' => 0})
# a11 = Player.new({'first_name' => 'Gabriel', 'last_name' => 'Batistuta', 'country_id' => team8.id, 'position' => 'Striker', 'goals' => 0})

# g1 = Player.new({'first_name' => 'Andreas', 'last_name' => 'Kopke', 'country_id' => team9.id, 'position' => 'Goalkeeper', 'goals' => 0})
# g2 = Player.new({'first_name' => 'Jorg', 'last_name' => 'Heinrich', 'country_id' => team9.id, 'position' => 'Defender', 'goals' => 0})
# g3 = Player.new({'first_name' => 'Christian', 'last_name' => 'Worns', 'country_id' => team9.id, 'position' => 'Defender', 'goals' => 0})
# g4 = Player.new({'first_name' => 'Lothar', 'last_name' => 'Matthaus', 'country_id' => team9.id, 'position' => 'Defender', 'goals' => 0})
# g5 = Player.new({'first_name' => 'Jurgen', 'last_name' => 'Kohler', 'country_id' => team9.id, 'position' => 'Defender', 'goals' => 0})
# g6 = Player.new({'first_name' => 'Michael', 'last_name' => 'Tarnat', 'country_id' => team9.id, 'position' => 'Defender', 'goals' => 0})
# g7 = Player.new({'first_name' => 'Dietmar', 'last_name' => 'Hamann', 'country_id' => team9.id, 'position' => 'Midfielder', 'goals' => 0})
# g8 = Player.new({'first_name' => 'Jens', 'last_name' => 'Jeremies', 'country_id' => team9.id, 'position' => 'Midfielder', 'goals' => 0})
# g9 = Player.new({'first_name' => 'Thomas', 'last_name' => 'Hassler', 'country_id' => team9.id, 'position' => 'Midfielder', 'goals' => 0})
# g10 = Player.new({'first_name' => 'Oliver', 'last_name' => 'Bierhoff', 'country_id' => team9.id, 'position' => 'Striker', 'goals' => 0})
# g11 = Player.new({'first_name' => 'Jurgen', 'last_name' => 'Klinsmann', 'country_id' => team9.id, 'position' => 'Striker', 'goals' => 0})

# d1 = Player.new({'first_name' => 'Peter', 'last_name' => 'Schmeichel', 'country_id' => team10.id, 'position' => 'Goalkeeper', 'goals' => 0})
# d2 = Player.new({'first_name' => 'Michael', 'last_name' => 'Schjonberg', 'country_id' => team10.id, 'position' => 'Defender', 'goals' => 0})
# d3 = Player.new({'first_name' => 'Marc', 'last_name' => 'Rieper', 'country_id' => team10.id, 'position' => 'Defender', 'goals' => 0})
# d4 = Player.new({'first_name' => 'Jes', 'last_name' => 'Hogh', 'country_id' => team10.id, 'position' => 'Defender', 'goals' => 0})
# d5 = Player.new({'first_name' => 'Thomas', 'last_name' => 'Helveg', 'country_id' => team10.id, 'position' => 'Defender', 'goals' => 0})
# d6 = Player.new({'first_name' => 'Soren', 'last_name' => 'Colding', 'country_id' => team10.id, 'position' => 'Defender', 'goals' => 0})
# d7 = Player.new({'first_name' => 'Michael', 'last_name' => 'Laudrup', 'country_id' => team10.id, 'position' => 'Midfielder', 'goals' => 0})
# d8 = Player.new({'first_name' => 'Morten', 'last_name' => 'Wieghorst', 'country_id' => team10.id, 'position' => 'Midfielder', 'goals' => 0})
# d9 = Player.new({'first_name' => 'Martin', 'last_name' => 'Jorgensen', 'country_id' => team10.id, 'position' => 'Midfielder', 'goals' => 0})
# d10 = Player.new({'first_name' => 'Brian', 'last_name' => 'Laudrup', 'country_id' => team10.id, 'position' => 'Striker', 'goals' => 0})
# d11 = Player.new({'first_name' => 'Ebbe', 'last_name' => 'Sand', 'country_id' => team10.id, 'position' => 'Striker', 'goals' => 0})

# e1 = Player.new({'first_name' => 'David', 'last_name' => 'Seaman', 'country_id' => team11.id, 'position' => 'Goalkeeper', 'goals' => 0})
# e2 = Player.new({'first_name' => 'Gary', 'last_name' => 'Neville', 'country_id' => team11.id, 'position' => 'Defender', 'goals' => 0})
# e3 = Player.new({'first_name' => 'Tony', 'last_name' => 'Adams', 'country_id' => team11.id, 'position' => 'Defender', 'goals' => 0})
# e4 = Player.new({'first_name' => 'Sol', 'last_name' => 'Campbell', 'country_id' => team11.id, 'position' => 'Defender', 'goals' => 0})
# e5 = Player.new({'first_name' => 'Graeme', 'last_name' => 'Le Saux', 'country_id' => team11.id, 'position' => 'Defender', 'goals' => 0})
# e6 = Player.new({'first_name' => 'David', 'last_name' => 'Beckham', 'country_id' => team11.id, 'position' => 'Defender', 'goals' => 0})
# e7 = Player.new({'first_name' => 'Paul', 'last_name' => 'Ince', 'country_id' => team11.id, 'position' => 'Midfielder', 'goals' => 0})
# e8 = Player.new({'first_name' => 'Paul', 'last_name' => 'Scholes', 'country_id' => team11.id, 'position' => 'Midfielder', 'goals' => 0})
# e9 = Player.new({'first_name' => 'Darren', 'last_name' => 'Anderton', 'country_id' => team11.id, 'position' => 'Midfielder', 'goals' => 0})
# e10 = Player.new({'first_name' => 'Michael', 'last_name' => 'Owen', 'country_id' => team11.id, 'position' => 'Striker', 'goals' => 0})
# e11 = Player.new({'first_name' => 'Alan', 'last_name' => 'Shearer', 'country_id' => team11.id, 'position' => 'Striker', 'goals' => 0})